import { principles, tasks } from './data.js';
const captureWidth = Number(new URLSearchParams(location.search).get('capture'));
if (captureWidth) {
  document.documentElement.classList.add('capture-wide');
  document.documentElement.style.setProperty('--capture-width', `${captureWidth}px`);
}
const app = document.querySelector('#app');
const state = { selected:null, attempts:0, diagnosed:null, order:[...tasks.repair.sizes], history:[], message:'', success:false };
const colors=['var(--red)','var(--blue)','var(--yellow)','var(--black)','var(--green)','var(--red)'];
const go=h=>location.hash=h;
const btn=(label,cls='primary-button',id='')=>`<button type="button" class="${cls}" ${id?`id="${id}"`:''}>${label}</button>`;
const dot=(size,i,extra='')=>`<span class="dot ${extra}" style="--size:${size}px;--dot-color:${colors[i%colors.length]}" aria-hidden="true"></span>`;

function renderHome(){app.innerHTML=`<section class="home" aria-labelledby="home-title"><div class="home-copy"><p class="home-kicker">視覺藝術・形式原理</p><h1 class="home-title" id="home-title"><span>形式原理</span><span>視覺實驗室</span></h1><p class="home-subtitle">觀察・比較・調整<br>找出畫面中的秩序</p>${btn('進入實驗室','primary-button','enter-lab')}</div><div class="hero-art" aria-label="以圓點呈現重複、漸層、對比與均衡的抽象構圖"><i class="hero-axis" aria-hidden="true"></i>${Array.from({length:14},(_,i)=>`<i class="hero-dot d${i+1}" aria-hidden="true"></i>`).join('')}</div></section>`;document.querySelector('#enter-lab').onclick=()=>go('#principles');}
function sampleDots(p){return `<div class="mini-dots ${p.id}">${p.dots.map((s,i)=>dot(s,i)).join('')}</div>`;}
function renderPrinciples(){app.innerHTML=`<section class="wall page-shell"><header class="wall-header"><button class="back-link" id="home-back">← 回到入口</button><div><p class="section-label">實驗樣本牆</p><h1>選擇形式原理</h1></div><p>先從「漸層」開始，觀察變化如何形成秩序。</p></header><div class="sample-wall">${principles.map((p,i)=>`<article class="sample sample-${i+1} ${p.status==='open'?'available':''}"><div class="sample-visual">${sampleDots(p)}</div><div class="sample-copy"><span class="sample-no">0${i+1}</span><h2>${p.name}</h2><p>${p.description}</p>${p.status==='open'?`<button class="sample-enter" data-open>開始實驗 →</button>`:`<span class="sample-status">即將開放</span>`}</div></article>`).join('')}</div></section>`;document.querySelector('#home-back').onclick=()=>go('#home');document.querySelector('[data-open]').onclick=()=>{resetTask();go('#task-observe');};}
function taskFrame(t,canvas,controls,feedback=''){return `<section class="task-page page-shell"><header class="task-header"><button class="back-link" id="task-back">← 返回形式原理選擇頁</button><h1>${t.name}</h1><span class="progress">${t.step}／3</span></header><div class="task-prompt"><p class="section-label">漸層實驗</p><h2>${t.question}</h2></div><div class="artboard-wrap">${canvas}</div><div class="task-footer"><div class="feedback" role="status">${feedback}</div><div class="task-actions">${controls}</div></div></section>`;}
const bindBack=()=>document.querySelector('#task-back').onclick=()=>go('#principles');
function resetTask(){Object.assign(state,{selected:null,attempts:0,diagnosed:null,order:[...tasks.repair.sizes],history:[],message:'',success:false});}

function renderObserve(){const t=tasks.observe;const canvas=`<div class="choice-grid" aria-label="三張圓點構圖">${t.choices.map((c,i)=>`<button class="choice-art ${state.selected===c.id?'selected':''} ${state.attempts>=2&&!c.correct?'reobserve':''}" data-choice="${c.id}" aria-pressed="${state.selected===c.id}"><span class="choice-label">作品 ${String.fromCharCode(65+i)}</span><span class="choice-dots ${state.success&&c.correct?'sequence-glow':''}">${c.sizes.map((s,j)=>dot(s,j)).join('')}</span></button>`).join('')}</div>`;const controls=`${btn('提示','secondary-button','hint')}${btn('完成檢測','primary-button compact','check')}${state.success?btn('下一個任務','primary-button compact','next'):''}`;app.innerHTML=taskFrame(t,canvas,controls,state.success?`<strong>${t.success}</strong>`:state.message);bindBack();document.querySelectorAll('[data-choice]').forEach(el=>el.onclick=()=>{state.selected=el.dataset.choice;state.message='';renderObserve();});document.querySelector('#hint').onclick=()=>{state.message=t.hint;renderObserve();};document.querySelector('#check').onclick=()=>{if(!state.selected){state.message='請先選擇一張作品，再完成檢測。';}else if(t.choices.find(c=>c.id===state.selected).correct){state.success=true;}else{state.attempts++;state.message=t.hint;}renderObserve();};document.querySelector('#next')?.addEventListener('click',()=>{state.success=false;state.message='';state.attempts=0;go('#task-diagnose');});}
function renderDiagnose(){const t=tasks.diagnose,sizes=[...t.sizes];if(state.success)sizes[t.wrongIndex]=t.fixedSize;const canvas=`<div class="single-artboard"><div class="diagnose-row ${state.success?'restored':''}">${sizes.map((s,i)=>`<button class="diagnose-dot ${state.diagnosed===i?'selected':''} ${state.attempts>=2&&Math.abs(i-t.wrongIndex)<=1?'neighbor-hint':''}" data-index="${i}" aria-label="第 ${i+1} 顆圓點，直徑 ${s}"><span style="--size:${s}px;--dot-color:${colors[i]}"></span></button>`).join('')}</div><div class="baseline" aria-hidden="true"></div></div>`;const controls=`${btn('提示','secondary-button','hint')}${btn('完成檢測','primary-button compact','check')}${state.success?btn('下一個任務','primary-button compact','next'):''}`;app.innerHTML=taskFrame(t,canvas,controls,state.success?`<strong>${t.success}</strong>`:state.message);bindBack();document.querySelectorAll('[data-index]').forEach(el=>el.onclick=()=>{if(!state.success){state.diagnosed=Number(el.dataset.index);state.message='';renderDiagnose();}});document.querySelector('#hint').onclick=()=>{state.message=t.hint;renderDiagnose();};document.querySelector('#check').onclick=()=>{if(state.diagnosed===null)state.message='請先選出打亂漸層的圓點。';else if(state.diagnosed===t.wrongIndex)state.success=true;else{state.attempts++;state.message=t.hint;}renderDiagnose();};document.querySelector('#next')?.addEventListener('click',()=>{state.success=false;state.message='';state.attempts=0;go('#task-repair');});}
const ascending=a=>a.every((n,i)=>!i||n>a[i-1]);
function renderRepair(){const t=tasks.repair;const canvas=`<div class="single-artboard repair-board"><div class="slots" role="list" aria-label="可拖曳排序的六個圓點">${state.order.map((s,i)=>`<button class="drag-dot" draggable="true" data-pos="${i}" role="listitem" aria-label="直徑 ${s} 的圓點，目前第 ${i+1} 位。使用左右方向鍵移動。"><span style="--size:${s}px;--dot-color:${colors[t.sizes.indexOf(s)]}"></span><i>${i+1}</i></button>`).join('')}</div><div class="slot-line" aria-hidden="true"></div></div>`;app.innerHTML=taskFrame(t,canvas,`${btn('復原','secondary-button','undo')}${btn('提示','secondary-button','hint')}${btn('完成檢測','primary-button compact','check')}`,state.success?`<strong>${t.success}</strong>`:state.message);bindBack();bindDrag();document.querySelector('#undo').onclick=()=>{state.order=state.history.pop()||[...t.sizes];state.message='';state.success=false;renderRepair();};document.querySelector('#hint').onclick=()=>{state.message='從最小的圓點開始排列看看。';renderRepair();};document.querySelector('#check').onclick=()=>{if(ascending(state.order)){state.success=true;renderRepair();setTimeout(()=>go('#complete'),750);}else{const inv=state.order.filter((n,i)=>i&&n<=state.order[i-1]).length;state.message=inv===1?'有一處大小順序中斷了。':state.order[0]!==Math.min(...state.order)?'從最小的圓點開始排列看看。':'比較相鄰兩顆圓點的大小。';renderRepair();}};}
function moveItem(from,to){if(from===to||to<0||to>=state.order.length)return;state.history.push([...state.order]);const n=[...state.order],[item]=n.splice(from,1);n.splice(to,0,item);state.order=n;state.success=false;renderRepair();document.querySelector(`[data-pos="${to}"]`)?.focus();}
function bindDrag(){let from=null;document.querySelectorAll('.drag-dot').forEach(el=>{el.addEventListener('dragstart',()=>{from=+el.dataset.pos;el.classList.add('dragging');});el.addEventListener('dragend',()=>el.classList.remove('dragging'));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();moveItem(from,+el.dataset.pos);});el.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;from=+el.dataset.pos;el.setPointerCapture(e.pointerId);});el.addEventListener('pointerup',e=>{if(e.pointerType==='mouse')return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.drag-dot');if(target)moveItem(from,+target.dataset.pos);});el.addEventListener('keydown',e=>{const p=+el.dataset.pos;if(e.key==='ArrowLeft'){e.preventDefault();moveItem(p,p-1);}if(e.key==='ArrowRight'){e.preventDefault();moveItem(p,p+1);}});});}
function renderComplete(){app.innerHTML=`<section class="complete page-shell"><div class="complete-copy"><p class="section-label">觀察・比較・診斷・修正</p><h1>漸層實驗完成</h1><p>漸層不是只有大小不同，<br>而是依照順序持續產生變化。</p>${btn('回到實驗樣本牆','primary-button','back-wall')}</div><div class="complete-art" aria-label="六個圓點由小到大排列">${[18,28,38,48,58,70].map((s,i)=>dot(s,i)).join('')}<i aria-hidden="true"></i></div></section>`;document.querySelector('#back-wall').onclick=()=>go('#principles');}
function route(){const h=location.hash||'#home';({'#home':renderHome,'#principles':renderPrinciples,'#task-observe':renderObserve,'#task-diagnose':renderDiagnose,'#task-repair':renderRepair,'#complete':renderComplete}[h]||renderHome)();window.scrollTo(0,0);}
window.addEventListener('hashchange',route);route();
